INSERT INTO procedure(procedure_code,procedure_type,procedure_description) VALUES
('CLEAN','Teeth Cleaning','We will clean, polish, and rinse your teeth to remove any tartar and plaque that have built up on the surface of your teeth.'),
('WHITE','Teeth Whitening','Although teeth are not naturally meant to be completely white, many Canadians want a brighter smile. Responding to this desire, a wide range of "whitening" options has become available to consumers.'),
('ROOT','Root Canal','When a tooth is cracked or has a deep cavity, bacteria can enter the pulp tissue and germs can cause an infection inside the tooth. If left untreated, an abscess may form. If the infected tissue is not removed, pain and swelling can result. This can not only injure your jawbones, but it is also detrimental to your overall health.'),
('CFILL','Cavity Filling','There are two different kinds of fillings: direct and indirect. Direct fillings are fillings placed into a prepared cavity in a single visit. They include silver amalgam, glass ionomers, resin ionomers, and composite (resin) fillings. Indirect fillings generally require two or more visits. They include inlays, onlays, and veneers. They are used when a tooth has too much damage to support a filling but not enough to necessitate a crown.'),
('MOLAR','Wisdom Teeth Extraction','Wisdom teeth are types of molars found in the very back of your mouth. They usually appear in the late teens or early twenties, but may become impacted (fail to erupt) due to lack of room in the jaw or angle of entry. When a wisdom tooth is impacted, it may need to be removed. If it is not removed, you may develop gum tenderness, swelling, or even severe pain. Impacted wisdom teeth that are partially or fully erupted tend to be quite difficult to clean and are susceptible to tooth decay, recurring infections, and even gum disease.'),
('IMPLT','Dental Implant','Dental implants are used to replace missing roots and support replacement teeth.'),
('VENER','Bonding & Veneers','Bonding and veneers make your teeth look better by changing their colour, shape or spacing.'),
('XRAY','X-Ray & Imaging','Dental radiographs are commonly called X-rays. Dentists use radiographs for many reasons: to find hidden dental structures, malignant or benign masses, bone loss, and cavities.'),
('BRACE','Braces & Invisalign ','The goal is to straighten and correct crooked teeth, as straighter teeth are often healthier and easier to take care of. Classic braces use metal and other materials to slowly tighten teeth back into place. Invisalign is less visible and slower acting, but still a very effective method to achieve the same goal.');

SELECT * FROM procedure;
